apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: chaitanya751293/mern:frontendimage-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

  `````Commands:
--- kubectl apply -f deployment.yml
--- kubectl rollout status deployment node-app-deployment
--- kubectl rollout undo deployment node-app-deployment
--- kubectl scale deployment node-app-deployment --replicas=5
